In [1]:
import pandas as pd
def load_csv (file):
    return pd.read_csv(file)

In [2]:
national="Physician_Compare_National_Downloadable_File.csv"
national_df = load_csv(national)

/Users/yier.jin/miniconda3/envs/bio-py/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2802: DtypeWarning: Columns (15,25,26,27,28,29,30,31,32,33,34,36,40) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):

In [3]:
national_df.head(10)

,NPI,PAC ID,Professional Enrollment ID,Last Name,First Name,Middle Name,Suffix,Gender,Credential,Medical school name,...,Hospital affiliation CCN 3,Hospital affiliation LBN 3,Hospital affiliation CCN 4,Hospital affiliation LBN 4,Hospital affiliation CCN 5,Hospital affiliation LBN 5,Professional accepts Medicare Assignment,Reported Quality Measures,Used electronic health records,Committed to heart health through the Million HeartsÂ® initiative.
0,1487927612,4880850486,I20120726000331,HALL,ESTHER,S,NaN,F,NaN,LIFE CHIROPRACTIC COLLEGE - WEST,...,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN
1,1235146762,2365435336,I20040406000367,WHITE,BARBARA,L,NaN,F,CSW,OTHER,...,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN
2,1346282258,5395768527,I20060113000139,DAVIDSON,JOHN,A,NaN,M,CSW,OTHER,...,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN
3,1932283124,5193762862,I20050415000143,CAGEN,STEVEN,F,NaN,M,DC,SHERMAN COLLEGE OF STRAIGHT CHIROPRACTIC,...,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN
4,1902950462,7416123666,I20120110000522,ESPY,LEISHA,H,NaN,F,NaN,LIFE CHIROPRACTIC COLLEGE,...,NaN,NaN,NaN,NaN,NaN,NaN,M,NaN,NaN,NaN
5,1518981026,7719166586,I20110125001223,PETROSKY,DAN,M,NaN,M,NaN,OTHER,...,NaN,NaN,NaN,NaN,NaN,NaN,M,NaN,NaN,NaN
6,1972698736,5294726436,I20040518001235,JANAS,INNA,NaN,NaN,F,MD,OTHER,...,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN
7,1700875143,446430474,I20110209000236,DEPAZ REYES,BERNARDO,A,NaN,M,NaN,OTHER,...,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN
8,1598766461,7719970664,I20040406001040,CRESS,DIANE,L,NaN,F,OD,STATE UNIVERSITY OF NEW YORK - STATE COLLEGE O...,...,NaN,NaN,NaN,NaN,NaN,NaN,M,NaN,NaN,NaN
9,1477630564,4981768074,I20090211000545,BERGMAN,JEROD,J,NaN,M,NaN,NORTHWESTERN COLLEGE OF CHIROPRACTIC,...,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN

In [4]:
national_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2955262 entries, 0 to 2955261
Data columns (total 41 columns):
NPI                                                                  int64
PAC ID                                                               int64
Professional Enrollment ID                                           object
Last Name                                                            object
First Name                                                           object
Middle Name                                                          object
Suffix                                                               object
Gender                                                               object
Credential                                                           object
Medical school name                                                  object
Graduation year                                                      float64
Primary specialty                                                    object
Secondary specialty 1                                                object
Secondary specialty 2                                                object
Secondary specialty 3                                                object
Secondary specialty 4                                                object
All secondary specialties                                            object
Organization legal name                                              object
Group Practice PAC ID                                                float64
Number of Group Practice members                                     float64
Line 1 Street Address                                                object
Line 2 Street Address                                                object
Marker of address line 2 suppression                                 object
City                                                                 object
State                                                                object
Zip Code                                                             object
Phone Number                                                         object
Hospital affiliation CCN 1                                           object
Hospital affiliation LBN 1                                           object
Hospital affiliation CCN 2                                           object
Hospital affiliation LBN 2                                           object
Hospital affiliation CCN 3                                           object
Hospital affiliation LBN 3                                           object
Hospital affiliation CCN 4                                           object
Hospital affiliation LBN 4                                           object
Hospital affiliation CCN 5                                           float64
Hospital affiliation LBN 5                                           object
Professional accepts Medicare Assignment                             object
Reported Quality Measures                                            object
Used electronic health records                                       object
Committed to heart health through the Million HeartsÂ® initiative.    object
dtypes: float64(4), int64(2), object(35)
memory usage: 924.4+ MB

In [8]:
national_df["NPI"].nunique()

1070395

In [6]:
national_df["PAC ID"].nunique()

1070399

## No.2 ratio

In [31]:
credential_df = national_df[["Gender","Credential"]]

In [36]:
credential_df_clean = credential_df.dropna()

In [51]:
data = credential_df_clean.groupby(["Credential","Gender"]).size()

In [54]:
data.head()

Credential  Gender
AA          F           248
            M           275
AU          F          1907
            M           569
CNA         F         15484
dtype: int64

In [55]:
data_unstack = data.unstack()

In [60]:
data_unstack.head()

Gender            F        M   U
Credential
AA            248.0    275.0 NaN
AU           1907.0    569.0 NaN
CNA         15484.0  13007.0 NaN
CNM          2202.0     12.0 NaN
CNS          2074.0    142.0 NaN

In [61]:
data_unstack["ratio"] = data_unstack["F"]/data_unstack["M"]

In [65]:
data_unstack.sort_values("ratio")

Gender             F         M    U       ratio
Credential
DDS             68.0     990.0  NaN    0.068687
DDM             66.0     363.0  NaN    0.181818
DPM           2841.0   11626.0  NaN    0.244366
DC            4798.0   17291.0  1.0    0.277485
MD          175835.0  534876.0  NaN    0.328740
DO           10751.0   31623.0  NaN    0.339974
OD            7388.0   12820.0  NaN    0.576287
PT           10753.0   12060.0  NaN    0.891625
AA             248.0     275.0  NaN    0.901818
PSY            121.0     122.0  NaN    0.991803
CP            7218.0    6281.0  NaN    1.149180
CNA          15484.0   13007.0  NaN    1.190436
PA           36839.0   25266.0  NaN    1.458046
AU            1907.0     569.0  NaN    3.351494
CSW          11884.0    3396.0  NaN    3.499411
OT            2109.0     463.0  NaN    4.555076
NP           43668.0    4639.0  NaN    9.413236
CNS           2074.0     142.0  NaN   14.605634
MNT           1483.0      46.0  NaN   32.239130
CNM           2202.0      12.0  NaN  183.500000
SCW              1.0       NaN  NaN         NaN

### 3 performance

In [66]:
Performence="Physician_Compare_2015_Individual_EP_Public_Reporting___Performance_Scores.csv"
Performence_df = load_csv(Performence)

In [68]:
Performence_df.head(100)

,NPI,PAC ID,Last Name,First Name,Measure Identifier,Measure Title,Inverse Measure,Measure Performance Rate,Reporting Mechanism,Reported on PC Live Site
0,1508823618,42100117,GRIFFIN,DAVID,PQRS_EP_110_1,Preventive Care and Screening: Influenza Immun...,N,21,CLM,Y
1,1508823618,42100117,GRIFFIN,DAVID,PQRS_EP_111_1,Pneumonia Vaccination Status for Older Adults,N,28,CLM,Y
2,1508823618,42100117,GRIFFIN,DAVID,PQRS_EP_112_1,Breast Cancer Screening,N,37,CLM,Y
3,1508823618,42100117,GRIFFIN,DAVID,PQRS_EP_113_1,Colorectal Cancer Screening,N,22,CLM,Y
4,1508823618,42100117,GRIFFIN,DAVID,PQRS_EP_128_1,Preventive Care and Screening: Body Mass Index...,N,42,CLM,Y
5,1508823618,42100117,GRIFFIN,DAVID,PQRS_EP_130_1,Documentation of Current Medications in the Me...,N,92,CLM,Y
6,1508823618,42100117,GRIFFIN,DAVID,PQRS_EP_181_1,Elder Maltreatment Screen and Follow-Up Plan,N,0,CLM,Y
7,1508823618,42100117,GRIFFIN,DAVID,PQRS_EP_226_1,Preventive Care and Screening: Tobacco Use: Sc...,N,98,CLM,Y
8,1508823618,42100117,GRIFFIN,DAVID,PQRS_EP_39_1,Screening or Therapy for Osteoporosis for Wome...,N,40,CLM,Y
9,1477528776,42100133,SPEAR,JEFFREY,PQRS_EP_317_1,Preventive Care and Screening: Screening for H...,N,37,CLM,Y
10,1477528776,42100133,SPEAR,JEFFREY,PQRS_EP_54_1,Emergency Medicine: 12-Lead Electrocardiogram ...,N,100,REG,Y
11,1154338044,42100190,VERBRUGGE,JOHN,PQRS_EP_317_1,Preventive Care and Screening: Screening for H...,N,96,CLM,Y
12,1982641247,42100273,JOHN,SAJI,PQRS_EP_130_1,Documentation of Current Medications in the Me...,N,1,CLM,Y
13,1285691733,42100323,LAPLANTE,DRUANNE,PQRS_EP_110_1,Preventive Care and Screening: Influenza Immun...,N,55,CLM,Y
14,1285691733,42100323,LAPLANTE,DRUANNE,PQRS_EP_111_1,Pneumonia Vaccination Status for Older Adults,N,80,CLM,Y
15,1285691733,42100323,LAPLANTE,DRUANNE,PQRS_EP_112_1,Breast Cancer Screening,N,77,CLM,Y
16,1285691733,42100323,LAPLANTE,DRUANNE,PQRS_EP_128_1,Preventive Care and Screening: Body Mass Index...,N,38,CLM,Y
17,1285691733,42100323,LAPLANTE,DRUANNE,PQRS_EP_130_1,Documentation of Current Medications in the Me...,N,96,CLM,Y
18,1285691733,42100323,LAPLANTE,DRUANNE,PQRS_EP_226_1,Preventive Care and Screening: Tobacco Use: Sc...,N,97,CLM,Y
19,1033197512,42100547,REMANDABAN,TEODULO,PQRS_EP_193_1,Perioperative Temperature Management,N,100,CLM,Y
20,1447242219,42100687,PINTO,ANTHONY,PQRS_EP_193_1,Perioperative Temperature Management,N,100,CLM,Y
21,1922007376,42100968,PREBISH,RICHARD,PQRS_EP_131_1,Pain Assessment and Follow-Up,N,100,CLM,Y
22,1922007376,42100968,PREBISH,RICHARD,PQRS_EP_182_1,Functional Outcome Assessment,N,100,CLM,Y
23,1881799146,42101156,NATH,MANOJ,PQRS_EP_130_1,Documentation of Current Medications in the Me...,N,100,CLM,Y
24,1033183900,42101164,HEARLD,DANIEL,PQRS_EP_317_1,Preventive Care and Screening: Screening for H...,N,78,CLM,Y
25,1417040411,42101214,TANTRA,ZUBIN,PQRS_EP_128_1,Preventive Care and Screening: Body Mass Index...,N,56,CLM,Y
26,1417040411,42101214,TANTRA,ZUBIN,PQRS_EP_131_1,Pain Assessment and Follow-Up,N,100,CLM,Y
27,1417040411,42101214,TANTRA,ZUBIN,PQRS_EP_182_1,Functional Outcome Assessment,N,100,CLM,Y
28,1235291907,42101248,HILL,WILLIAM,PQRS_EP_130_1,Documentation of Current Medications in the Me...,N,69,CLM,Y
29,1235291907,42101248,HILL,WILLIAM,PQRS_EP_131_1,Pain Assessment and Follow-Up,N,100,CLM,Y
...,...,...,...,...,...,...,...,...,...,...
70,1720036304,42102741,REDD,JASON,PQRS_EP_317_1,Preventive Care and Screening: Screening for H...,N,64,CLM,Y
71,1164406310,42103053,BEALE,SARAH,PQRS_EP_195_1,Radiology: Stenosis Measurement in Carotid Ima...,N,86,CLM,Y
72,1447285739,42103442,ALONSO,OSCAR,PQRS_EP_128_1,Preventive Care and Screening: Body Mass Index...,N,100,CLM,Y
73,1447285739,42103442,ALONSO,OSCAR,PQRS_EP_130_1,Documentation of Current Medications in the Me...,N,100,CLM,Y
74,1447285739,42103442,ALONSO,OSCAR,PQRS_EP_226_1,Preventive Care and Screening: Tobacco Use: Sc...,N,100,CLM,Y
75,1447285739,42103442,ALONSO,OSCAR,PQRS_EP_46_2,Medication Reconciliation,N,100,CLM,Y
76,1790779171,42103459,HANSEN,DAVID,PQRS_EP_131_1,Pain Assessment and Follow-Up,N,99,CLM,Y
77,1790779171,42103459,HANSEN,DAVID,PQRS_EP_182_1,Functional Outcome Assessment,N,68,CLM,Y
78,1740265263,42103483,AALUND,GORDON,PQRS_EP_317_1,Preventive Care and Screening: Screening for H...,N,56,CLM,Y
79,1538157904,42103723,ANNAMRAJU,SRINIVAS,PQRS_EP_145_1,Radiology: Exposure Time Reported for Procedur...,N,98,CLM,Y
80,1538157904,42103723,ANNAMRAJU,SRINIVAS,PQRS_EP_195_1,Radiology: Stenosis Measurement in Carotid Ima...,N,98,CLM,Y
81,1386608347,42103764,SCHILSKY,RANDY,PQRS_EP_131_1,Pain Assessment and Follow-Up,N,100,CLM,Y
82,1386608347,42103764,SCHILSKY,RANDY,PQRS_EP_182_1,Functional Outcome Assessment,N,100,CLM,Y
83,1639196496,42103822,SUNDSTROM,JAIME,PQRS_EP_128_1,Preventive Care and Screening: Body Mass Index...,N,15,CLM,Y
84,1851380232,42104093,STARKWEATHER,GEORGE,PQRS_EP_193_1,Perioperative Temperature Management,N,97,CLM,Y
85,1487778502,42104127,MILLER,RACHEL,PQRS_EP_128_1,Preventive Care and Screening: Body Mass Index...,N,40,CLM,Y
86,1487778502,42104127,MILLER,RACHEL,PQRS_EP_130_1,Documentation of Current Medications in the Me...,N,3,CLM,Y
87,1881634996,42104408,WEBB,MICHAEL,PQRS_EP_145_1,Radiology: Exposure Time Reported for Procedur...,N,73,CLM,Y
88,1881634996,42104408,WEBB,MICHAEL,PQRS_EP_76_1,Prevention of Central Venous Catheter (CVC)-Re...,N,4,CLM,Y
89,1285715409,42104507,SAKHAROVA,ALLA,PQRS_EP_117_1,Diabetes: Eye Exam,N,100,CLM,Y
90,1285715409,42104507,SAKHAROVA,ALLA,PQRS_EP_119_1,Diabetes: Medical Attention for Nephropathy,N,100,CLM,Y
91,1285715409,42104507,SAKHAROVA,ALLA,PQRS_EP_128_1,Preventive Care and Screening: Body Mass Index...,N,100,CLM,Y
92,1285715409,42104507,SAKHAROVA,ALLA,PQRS_EP_130_1,Documentation of Current Medications in the Me...,N,98,CLM,Y
93,1285715409,42104507,SAKHAROVA,ALLA,PQRS_EP_163_1,Diabetes: Foot Exam,N,100,CLM,Y
94,1285715409,42104507,SAKHAROVA,ALLA,PQRS_EP_317_1,Preventive Care and Screening: Screening for H...,N,100,CLM,Y
95,1285715409,42104507,SAKHAROVA,ALLA,PQRS_EP_46_2,Medication Reconciliation,N,15,CLM,Y
96,1689755910,42104796,HENDRIKSON,ROBERT,PQRS_EP_128_1,Preventive Care and Screening: Body Mass Index...,N,9,CLM,Y
97,1689755910,42104796,HENDRIKSON,ROBERT,PQRS_EP_130_1,Documentation of Current Medications in the Me...,N,81,CLM,Y
98,1689755910,42104796,HENDRIKSON,ROBERT,PQRS_EP_226_1,Preventive Care and Screening: Tobacco Use: Sc...,N,93,CLM,Y
99,1922085943,42104929,NACKLEY,GEORGE,PQRS_EP_226_1,Preventive Care and Screening: Tobacco Use: Sc...,N,100,CLM,Y

In [87]:
Performence_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 495417 entries, 0 to 495416
Data columns (total 10 columns):
NPI                         495417 non-null int64
PAC ID                      495417 non-null int64
Last Name                   495411 non-null object
First Name                  495417 non-null object
Measure Identifier          495417 non-null object
Measure Title               495417 non-null object
Inverse Measure             495417 non-null object
Measure Performance Rate    495417 non-null int64
Reporting Mechanism         495417 non-null object
Reported on PC Live Site    495417 non-null object
dtypes: int64(3), object(7)
memory usage: 37.8+ MB

In [69]:
per = Performence_df[["NPI","Measure Performance Rate"]]

In [74]:
mean = per.groupby("NPI").mean()

In [79]:
mean.shape

(180723, 1)

In [77]:
mean_10above = mean[mean["Measure Performance Rate"]>10]

In [80]:
mean_10above.shape

(176829, 1)

In [97]:
mean_10above.head(10)

            Measure Performance Rate
NPI
1003000142                 46.125000
1003000407                 76.000000
1003000704                100.000000
1003000829                 98.000000
1003001371                 91.000000
1003001785                100.000000
1003002072                 96.333333
1003002098                100.000000
1003002379                 95.000000
1003002783                100.000000

In [84]:
mean_10above["Measure Performance Rate"].std()

22.412960071640533

In [85]:
mean_10below = mean[mean["Measure Performance Rate"]<10]

### 3 performance difference between MD and NP

In [107]:
matrix1 = national_df[["NPI","Credential"]]
matrix1_nona = matrix1.dropna()
matrix1_nona.head(10)

           NPI Credential
1   1235146762        CSW
2   1346282258        CSW
3   1932283124         DC
6   1972698736         MD
8   1598766461         OD
10  1114092335         MD
16  1487766671         DC
17  1629125588        CSW
18  1932179165        CSW
20  1013012434         DC

In [110]:
matrix2 = Performence_df[["NPI","Measure Performance Rate"]]

In [113]:
matrix2.head()

          NPI  Measure Performance Rate
0  1508823618                        21
1  1508823618                        28
2  1508823618                        37
3  1508823618                        22
4  1508823618                        42

In [114]:
merge = pd.merge(matrix1_nona, matrix2, on='NPI')

In [115]:
merge.head()

          NPI Credential  Measure Performance Rate
0  1003958174         PT                       100
1  1003958174         PT                       100
2  1548322357         DC                       100
3  1548322357         DC                       100
4  1548322357         DC                       100

In [118]:
merge_mean = merge.groupby(["Credential","NPI"]).mean()

In [121]:
merge_mean.head(10)

                       Measure Performance Rate
Credential NPI
AA         1003874074                     100.0
           1013903046                     100.0
           1023004942                      97.0
           1053358838                      96.0
           1063457729                     100.0
           1063460236                      96.0
           1063474351                      80.0
           1093761975                     100.0
           1114961695                      97.0
           1114989449                      65.0

In [238]:
## for last question:
re_merge_mean1 = merge_mean.reset_index()
re_merge_mean1.head()

  Credential         NPI  Measure Performance Rate
0         AA  1003874074                     100.0
1         AA  1013903046                     100.0
2         AA  1023004942                      97.0
3         AA  1053358838                      96.0
4         AA  1063457729                     100.0

In [249]:
### for last question
MD = re_merge_mean1[re_merge_mean1.Credential == "MD"]
MD.head()

      Credential         NPI  Measure Performance Rate
13068         MD  1003003856                 15.000000
13069         MD  1003010349                 40.555556
13070         MD  1003015553                 98.666667
13071         MD  1003027335                100.000000
13072         MD  1003033838                100.000000

In [250]:
### for last question
NP = re_merge_mean1[re_merge_mean1.Credential == "NP"]
NP.head()

      Credential         NPI  Measure Performance Rate
56866         NP  1003826991                 54.222222
56867         NP  1003831017                100.000000
56868         NP  1003839424                 27.000000
56869         NP  1003846122                 96.000000
56870         NP  1003848516                 63.500000

In [124]:
merge_mean_10above=merge_mean[merge_mean["Measure Performance Rate"]>10]

In [125]:
merge_mean.shape

(66882, 1)

In [126]:
merge_mean_10above.shape

(65321, 1)

In [127]:
merge_mean_10above.groupby("Credential").mean()

            Measure Performance Rate
Credential
AA                         96.247059
AU                         84.639655
CNA                        95.334566
CNM                        74.781015
CNS                        82.638974
CP                         94.802931
CSW                        93.927763
DC                         95.487847
DDM                        81.500000
DDS                        65.840000
DO                         77.882248
DPM                        78.645296
MD                         79.039928
MNT                        75.584375
NP                         73.644659
OD                         93.280775
OT                         92.557932
PA                         69.072670
PSY                        98.000000
PT                         94.349544

In [128]:
print(abs(79.039928-73.644659))

5.395268999999999

### ratio of male to female clinitians

In [131]:
gender = national_df[["NPI","Gender"]]

In [132]:
gender.head()

          NPI Gender
0  1487927612      F
1  1235146762      F
2  1346282258      M
3  1932283124      M
4  1902950462      F

In [133]:
gender.groupby("Gender").size()

Gender
F    1280809
M    1674452
U          1
dtype: int64

In [134]:
print("male to female ratio = ", 1674452/1280809)

male to female ratio =  1.3073393456791762

### hospital faciliation

In [137]:
m ="Physician_Compare_2015_Group_Public_Reporting___Performance_Scores.csv"
m_df = load_csv(m)
m_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11117 entries, 0 to 11116
Data columns (total 11 columns):
Organization legal name or 'doing business as' name    11117 non-null object
Group PAC ID                                           11117 non-null int64
State                                                  11117 non-null object
Participating in PQRS                                  10702 non-null object
Measure Identifier                                     11117 non-null object
Measure Title                                          11117 non-null object
Inverse Measure                                        11117 non-null object
Measure Performance Rate                               10671 non-null float64
Footnote                                               446 non-null float64
Reporting Mechanism                                    11117 non-null object
Reported on PC Live Site                               11117 non-null object
dtypes: float64(2), int64(1), object(8)
memory usage: 955.4+ KB

In [139]:
m_df.head(100)

,Organization legal name or 'doing business as' name,Group PAC ID,State,Participating in PQRS,Measure Identifier,Measure Title,Inverse Measure,Measure Performance Rate,Footnote,Reporting Mechanism,Reported on PC Live Site
0,GLEN BURNIE PHYSICAL THERAPY AND SPORTSCARE LLC,42102592,MD,NaN,PQRS_GRP_131_1,Pain Assessment and Follow-Up,N,99.0,NaN,REG,Y
1,GLEN BURNIE PHYSICAL THERAPY AND SPORTSCARE LLC,42102592,MD,NaN,PQRS_GRP_154_1,Falls: Risk Assessment,N,77.0,NaN,REG,Y
2,GLEN BURNIE PHYSICAL THERAPY AND SPORTSCARE LLC,42102592,MD,NaN,PQRS_GRP_155_1,Falls: Plan of Care,N,88.0,NaN,REG,Y
3,GLEN BURNIE PHYSICAL THERAPY AND SPORTSCARE LLC,42102592,MD,NaN,PQRS_GRP_182_1,Functional Outcome Assessment,N,100.0,NaN,REG,Y
4,HERITAGE VALLEY MEDICAL GROUP INC,42105678,PA,Y,PQRS_GRP_110_1,Preventive Care and Screening: Influenza Immun...,N,62.0,NaN,WI,Y
5,HERITAGE VALLEY MEDICAL GROUP INC,42105678,PA,Y,PQRS_GRP_111_1,Pneumonia Vaccination Status for Older Adults,N,75.0,NaN,WI,Y
6,HERITAGE VALLEY MEDICAL GROUP INC,42105678,PA,Y,PQRS_GRP_112_1,Breast Cancer Screening,N,70.0,NaN,WI,Y
7,HERITAGE VALLEY MEDICAL GROUP INC,42105678,PA,Y,PQRS_GRP_113_1,Colorectal Cancer Screening,N,65.0,NaN,WI,Y
8,HERITAGE VALLEY MEDICAL GROUP INC,42105678,PA,Y,PQRS_GRP_117_1,Diabetes: Eye Exam,N,55.0,NaN,WI,Y
9,HERITAGE VALLEY MEDICAL GROUP INC,42105678,PA,Y,PQRS_GRP_118_1,Coronary Artery Disease (CAD): Angiotensin-Con...,N,77.0,NaN,WI,Y
10,HERITAGE VALLEY MEDICAL GROUP INC,42105678,PA,Y,PQRS_GRP_128_1,Preventive Care and Screening: Body Mass Index...,N,45.0,NaN,WI,Y
11,HERITAGE VALLEY MEDICAL GROUP INC,42105678,PA,Y,PQRS_GRP_130_1,Documentation of Current Medications in the Me...,N,71.0,NaN,WI,Y
12,HERITAGE VALLEY MEDICAL GROUP INC,42105678,PA,Y,PQRS_GRP_134_1,Preventive Care and Screening: Screening for C...,N,9.0,NaN,WI,Y
13,HERITAGE VALLEY MEDICAL GROUP INC,42105678,PA,Y,PQRS_GRP_204_1,Ischemic Vascular Disease (IVD): Use of Aspiri...,N,82.0,NaN,WI,Y
14,HERITAGE VALLEY MEDICAL GROUP INC,42105678,PA,Y,PQRS_GRP_226_1,Preventive Care and Screening: Tobacco Use: Sc...,N,89.0,NaN,WI,Y
15,HERITAGE VALLEY MEDICAL GROUP INC,42105678,PA,Y,PQRS_GRP_317_1,Preventive Care and Screening: Screening for H...,N,80.0,NaN,WI,Y
16,HERITAGE VALLEY MEDICAL GROUP INC,42105678,PA,Y,PQRS_GRP_318_1,Falls: Screening for Fall Risk,N,56.0,NaN,WI,Y
17,HERITAGE VALLEY MEDICAL GROUP INC,42105678,PA,Y,PQRS_GRP_8_1,Heart Failure (HF): Beta-Blocker Therapy for L...,N,NaN,2.0,WI,Y
18,YOUNG REHAB COMPANY PC,42107609,MI,NaN,PQRS_GRP_131_1,Pain Assessment and Follow-Up,N,100.0,NaN,REG,Y
19,YOUNG REHAB COMPANY PC,42107609,MI,NaN,PQRS_GRP_182_1,Functional Outcome Assessment,N,100.0,NaN,REG,Y
20,MAYO CLINIC HEALTH SYSTEM-OWATONNA,42111981,MN,Y,PQRS_GRP_110_1,Preventive Care and Screening: Influenza Immun...,N,84.0,NaN,WI,Y
21,MAYO CLINIC HEALTH SYSTEM-OWATONNA,42111981,MN,Y,PQRS_GRP_111_1,Pneumonia Vaccination Status for Older Adults,N,95.0,NaN,WI,Y
22,MAYO CLINIC HEALTH SYSTEM-OWATONNA,42111981,MN,Y,PQRS_GRP_112_1,Breast Cancer Screening,N,81.0,NaN,WI,Y
23,MAYO CLINIC HEALTH SYSTEM-OWATONNA,42111981,MN,Y,PQRS_GRP_113_1,Colorectal Cancer Screening,N,78.0,NaN,WI,Y
24,MAYO CLINIC HEALTH SYSTEM-OWATONNA,42111981,MN,Y,PQRS_GRP_117_1,Diabetes: Eye Exam,N,62.0,NaN,WI,Y
25,MAYO CLINIC HEALTH SYSTEM-OWATONNA,42111981,MN,Y,PQRS_GRP_118_1,Coronary Artery Disease (CAD): Angiotensin-Con...,N,88.0,NaN,WI,Y
26,MAYO CLINIC HEALTH SYSTEM-OWATONNA,42111981,MN,Y,PQRS_GRP_128_1,Preventive Care and Screening: Body Mass Index...,N,40.0,NaN,WI,Y
27,MAYO CLINIC HEALTH SYSTEM-OWATONNA,42111981,MN,Y,PQRS_GRP_130_1,Documentation of Current Medications in the Me...,N,56.0,NaN,WI,Y
28,MAYO CLINIC HEALTH SYSTEM-OWATONNA,42111981,MN,Y,PQRS_GRP_134_1,Preventive Care and Screening: Screening for C...,N,13.0,NaN,WI,Y
29,MAYO CLINIC HEALTH SYSTEM-OWATONNA,42111981,MN,Y,PQRS_GRP_204_1,Ischemic Vascular Disease (IVD): Use of Aspiri...,N,92.0,NaN,WI,Y
...,...,...,...,...,...,...,...,...,...,...,...
70,RADIATION THERAPY ASSOCIATES OF WESTERN NORTH ...,42246050,NC,Y,PQRS_GRP_71_1,Breast Cancer: Hormonal Therapy for Stage IC -...,N,87.0,NaN,REG,Y
71,"NEUROSURGICAL ASSOCIATES OF CENTRAL NEW YORK, LLP",42271520,NY,Y,PQRS_GRP_119_1,Diabetes: Medical Attention for Nephropathy,N,90.0,NaN,REG,Y
72,"NEUROSURGICAL ASSOCIATES OF CENTRAL NEW YORK, LLP",42271520,NY,Y,PQRS_GRP_173_1,Preventive Care and Screening: Unhealthy Alcoh...,N,100.0,NaN,REG,Y
73,VITTORIO M MORREALE MD PLC,42273864,MI,Y,PQRS_GRP_131_1,Pain Assessment and Follow-Up,N,1.0,NaN,REG,Y
74,VITTORIO M MORREALE MD PLC,42273864,MI,Y,PQRS_GRP_173_1,Preventive Care and Screening: Unhealthy Alcoh...,N,2.0,NaN,REG,Y
75,VITTORIO M MORREALE MD PLC,42273864,MI,Y,PQRS_GRP_181_1,Elder Maltreatment Screen and Follow-Up Plan,N,3.0,NaN,REG,Y
76,VITTORIO M MORREALE MD PLC,42273864,MI,Y,PQRS_GRP_238_1,Use of High-Risk Medications in the Elderly*,Y,6.0,NaN,REG,N
77,VITTORIO M MORREALE MD PLC,42273864,MI,Y,PQRS_GRP_238_2,Use of High-Risk Medications in the Elderly*,Y,2.0,NaN,REG,Y
78,VITTORIO M MORREALE MD PLC,42273864,MI,Y,PQRS_GRP_39_1,Screening or Therapy for Osteoporosis for Wome...,N,13.0,NaN,REG,Y
79,NEWTON WELLESLEY ORTHOPEDIC ASSOCIATES INC,42287591,MA,NaN,PQRS_GRP_109_1,Osteoarthritis (OA): Function and Pain Assessment,N,76.0,NaN,REG,Y
80,NEWTON WELLESLEY ORTHOPEDIC ASSOCIATES INC,42287591,MA,NaN,PQRS_GRP_131_1,Pain Assessment and Follow-Up,N,100.0,NaN,REG,Y
81,DERMATOLOGY ASSOCIATES OF NORTHWEST FLORIDA PA,42287872,FL,Y,PQRS_GRP_173_1,Preventive Care and Screening: Unhealthy Alcoh...,N,100.0,NaN,REG,Y
82,DERMATOLOGY ASSOCIATES OF NORTHWEST FLORIDA PA,42287872,FL,Y,PQRS_GRP_265_1,Biopsy Follow-Up,N,100.0,NaN,REG,Y
83,"MILLER ALLERGY, INC",42293177,OH,NaN,PQRS_GRP_53_1,Asthma: Pharmacologic Therapy for Persistent A...,N,79.0,NaN,REG,N
84,"MILLER ALLERGY, INC",42293177,OH,NaN,PQRS_GRP_53_3,Asthma: Pharmacologic Therapy for Persistent A...,N,79.0,NaN,REG,Y
85,SOUTHEASTERN PHYSICIAN SERVICES PC,42307852,KY,Y,PQRS_GRP_32_1,Stroke and Stroke Rehabilitation: Discharged o...,N,91.0,NaN,REG,Y
86,SOUTHEASTERN PHYSICIAN SERVICES PC,42307852,KY,Y,PQRS_GRP_33_1,Stroke and Stroke Rehabilitation: Anticoagulan...,N,91.0,NaN,REG,Y
87,SOUTHEASTERN PHYSICIAN SERVICES PC,42307852,KY,Y,PQRS_GRP_47_1,Care Plan,N,95.0,NaN,REG,Y
88,SOUTHEASTERN PHYSICIAN SERVICES PC,42307852,KY,Y,PQRS_GRP_76_1,Prevention of Central Venous Catheter (CVC)-Re...,N,88.0,NaN,REG,Y
89,"WASATCH PHYSICAL THERAPY AND REHABILITATION, INC",42349896,UT,Y,PQRS_GRP_131_1,Pain Assessment and Follow-Up,N,100.0,NaN,REG,Y
90,"WASATCH PHYSICAL THERAPY AND REHABILITATION, INC",42349896,UT,Y,PQRS_GRP_182_1,Functional Outcome Assessment,N,100.0,NaN,REG,Y
91,SOUTH GEORGIA RADIOLOGY ASSOCIATES LLC,42389231,GA,Y,PQRS_GRP_145_1,Radiology: Exposure Time Reported for Procedur...,N,78.0,NaN,REG,Y
92,SOUTH GEORGIA RADIOLOGY ASSOCIATES LLC,42389231,GA,Y,PQRS_GRP_146_1,Radiology: Inappropriate Use of ÂProbably Beni...,Y,0.0,NaN,REG,Y
93,SOUTH GEORGIA RADIOLOGY ASSOCIATES LLC,42389231,GA,Y,PQRS_GRP_147_1,Nuclear Medicine: Correlation with Existing Im...,N,59.0,NaN,REG,Y
94,SOUTH GEORGIA RADIOLOGY ASSOCIATES LLC,42389231,GA,Y,PQRS_GRP_195_1,Radiology: Stenosis Measurement in Carotid Ima...,N,99.0,NaN,REG,Y
95,SOUTH GEORGIA RADIOLOGY ASSOCIATES LLC,42389231,GA,Y,PQRS_GRP_225_1,Radiology: Reminder System for Screening Mammo...,N,100.0,NaN,REG,Y
96,SOUTH GEORGIA RADIOLOGY ASSOCIATES LLC,42389231,GA,Y,PQRS_GRP_324_1,Cardiac Stress Imaging Not Meeting Appropriate...,Y,1.0,NaN,REG,N
97,BARNABAS HEALTH MULTISPECIALTY,42441891,NJ,Y,PQRS_GRP_185_1,Colonoscopy Interval for Patients with a Histo...,N,98.0,NaN,REG,Y
98,BARNABAS HEALTH MULTISPECIALTY,42441891,NJ,Y,PQRS_GRP_320_1,Appropriate Follow-Up Interval for Normal Colo...,N,53.0,NaN,REG,Y
99,OLIVER STREET 5.01(A) INC.,42464125,TX,Y,PQRS_GRP_137_1,Melanoma: Continuity of Care Â Recall System,N,75.0,NaN,REG,Y

In [142]:
m_df_group = m_df.groupby(["State","Organization legal name or 'doing business as' name"]).size()

In [147]:
m_df_group.head(10)

State  Organization legal name or 'doing business as' name
AK     NORTH STAR MEDICAL IMAGING PLLC                         6
       PEACEHEALTH                                             4
       PROVIDENCE HEALTH AND SERVICES - WASHINGTON             3
       PROVIDENCE HEALTH AND SERVICES WASHINGTON               1
       SOUTHCENTRAL FOUNDATION                                14
       THE ALASKA HOSPITALIST GROUP LLC                        8
       UNITED PHYSICAL THERAPY, INC.                           3
AL     21ST CENTURY ONCOLOGY OF ALABAMA LLC                    4
       ALABAMA BONE AND JOINT CLINIC,LLC                       8
       ALABAMA ORTHOPAEDIC SPECIALISTS PA                      8
dtype: int64

In [148]:
m_df_count = m_df_group.groupby("State").count()

In [149]:
m_df_count.head()

State
AK      7
AL     35
AR     28
AZ     39
CA    139
dtype: int64

In [151]:
m_df_count[m_df_count<10].count()

9

### Linear regression

In [180]:
d1 = national_df[["NPI","Graduation year","Credential"]]

In [179]:
d1.head()

          NPI  Graduation year Credential
0  1487927612           2010.0        NaN
1  1235146762           1992.0        CSW
2  1346282258           1999.0        CSW
3  1932283124           1997.0         DC
4  1902950462           1985.0        NaN

In [182]:
d2 = d1[(d1.Credential == "MD")]

In [183]:
d2.head()

           NPI  Graduation year Credential
6   1972698736           1990.0         MD
10  1114092335           1984.0         MD
56  1306914536           1963.0         MD
67  1922016203           1967.0         MD
87  1609093319           1994.0         MD

In [184]:
d3 = d2[d2["Graduation year"]>=1973][d2["Graduation year"]<=2003]

/Users/yier.jin/miniconda3/envs/bio-py/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

In [195]:
d3.head()

            NPI  Graduation year Credential
6    1972698736           1990.0         MD
10   1114092335           1984.0         MD
87   1609093319           1994.0         MD
111  1336144872           1986.0         MD
147  1003889502           1992.0         MD

In [198]:
d3_merge = pd.merge(matrix2, d3, on='NPI')

In [199]:
d3_merge.head()

          NPI  Measure Performance Rate  Graduation year Credential
0  1508823618                        21           1996.0         MD
1  1508823618                        21           1996.0         MD
2  1508823618                        21           1996.0         MD
3  1508823618                        21           1996.0         MD
4  1508823618                        21           1996.0         MD

In [202]:
d4 = d3_merge.groupby("NPI").mean()

In [205]:
d4.head(10)

            Measure Performance Rate  Graduation year
NPI
1003003856                 15.000000           1997.0
1003010349                 40.555556           2003.0
1003015553                 98.666667           1987.0
1003027335                100.000000           1986.0
1003033838                100.000000           1997.0
1003037300                 77.000000           1974.0
1003076597                 67.200000           2000.0
1003093147                100.000000           1993.0
1003145038                 50.000000           1990.0
1003800145                 57.800000           1982.0

In [207]:
d5 = d4[d4["Measure Performance Rate"]>10]

In [208]:
print(d4.shape)
print(d5.shape)

(41539, 2)
(40468, 2)

In [209]:
d5.head()

            Measure Performance Rate  Graduation year
NPI
1003003856                 15.000000           1997.0
1003010349                 40.555556           2003.0
1003015553                 98.666667           1987.0
1003027335                100.000000           1986.0
1003033838                100.000000           1997.0

In [212]:
d6 = d5.groupby("Graduation year").mean()

In [217]:
d6.head(10)
d7 = d6.reset_index()
d7.head()

   Graduation year  Measure Performance Rate
0           1973.0                 78.527802
1           1974.0                 78.314540
2           1975.0                 75.156672
3           1976.0                 78.378455
4           1977.0                 78.714796

In [219]:
## linear regression

x, y = d7["Graduation year"],d7["Measure Performance Rate"]

In [220]:
from scipy import stats
slope, intercept, r_value, p_value, std_err = stats.linregress(x,y)

In [222]:
print(slope,p_value)

0.0579938055031 0.0107190701821

### T test

In [251]:
x = MD["Measure Performance Rate"]
y = NP["Measure Performance Rate"]

In [253]:
import numpy as np
import scipy.stats as stats
t_stat, p_val = stats.ttest_ind(x, y, equal_var=False)

print(t_stat, p_val)